In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
a=[1,2,3]
b=[4,5,6]
res=[]
for i in range(len(a)):
    res.append(a[i]+b[i])
print(res)

[5, 7, 9]


In [3]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [6]:
import numpy as np
arr=np.array([1,2,3,4,5])
ar=np.array([[1,2,3],[4,5,6]])
a=np.array([[[1,2],[3,4],[5,6]]])
print(arr)
print(ar)
print(a)
print(arr.ndim)
print(ar.shape)
print(a.ndim)
print(arr.size)
print(a.size)
print(a.dtype)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]
  [5 6]]]
1
(2, 3)
3
5
6
int32


In [7]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.zeros(5)
print(a)
print(b)
c=np.zeros((2,2))
print(c)
d=np.ones(3)
print(d)
e=np.ones((2,3))
print(e)


[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.zeros(5)
print(a)
print(b)
print(np.arange(1,10,2))
print(np.linspace(0,20,5))
print(np.random.rand(5))
print(np.random.randint(1,100,7))
print(np.random.randn(5))

[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[1 3 5 7 9]
[ 0.  5. 10. 15. 20.]
[0.23475261 0.28527751 0.57254806 0.70016081 0.78109226]
[64 75  8 50 59 96 27]
[ 2.66987739 -0.48649498  0.97695763 -0.30562713 -0.65663175]


## numpy slicing and indexing 

In [20]:
import numpy as np
a=np.array([10,20,30,40,50,60,70])
#1d array indexing
print(a[2])
b=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
#2d array indexing
print(b[1][1])
#1d slicing
print(a[2:6])
print(a[:4])
print(a[::2])
#2d slicing
print(b[1])
print(b[:,1])
print(a[a>50])
print(a[a<50])
print(a[[0,4,3,6]])
print(a[a%2==0])



30
5
[30 40 50 60]
[10 20 30 40]
[10 30 50 70]
[4 5 6]
[2 5 8]
[60 70]
[10 20 30 40]
[10 50 40 70]
[10 20 30 40 50 60 70]


## MATHEMATICAL OPERATION IN NUMPY

In [23]:
import numpy as np
#1d
a=np.array([1,2,3])
print(a+10)
#2d
b=np.array([[1,2,3],
            [4,5,6]])
print(b+10)
print(b+a)
#always no of col must be same

[11 12 13]
[[11 12 13]
 [14 15 16]]
[[2 4 6]
 [5 7 9]]


In [26]:
import numpy as np
a=np.array([[1,2],
            [3,4]])
b=np.array([[4,3],
            [2,1]])
print(a*b)
print(np.dot(a,b))
print(a@b)
print(np.matmul(a,b))
print(a.T)

[[4 6]
 [6 4]]
[[ 8  5]
 [20 13]]
[[ 8  5]
 [20 13]]
[[ 8  5]
 [20 13]]
[[1 3]
 [2 4]]


## UNIVERSAL MATHEMATICAL FUNCTION

In [ ]:
import numpy as np
a=np.array([4,9,6])
print(np.sqrt(a))
b=np.array([])

In [13]:
import numpy as np
a=np.array([10,20,30,40,50])
print(np.mean(a))
print(np.max(a))
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.percentile(a,100))
print(np.var(a))
print(np.argmin(a))
print(np.argmax(a))
b=np.array([1,2,3,4,5])
c=np.array([10,8,6,4,2])
print(np.corrcoef(b,c))
#aggregate function
d=np.array([[1,3,4],[5,6,8]])
print(np.sum(d))
print(np.sum(d,axis=1))
print(np.sum(d,axis=0))           

30.0
50
30.0
14.142135623730951
10
50.0
200.0
0
4
[[ 1. -1.]
 [-1.  1.]]
27
[ 8 19]
[ 6  9 12]


## statistical function

In [17]:
import numpy as np
stud=np.array([[85,70,45],
               [90,65,95],
               [75,49,82]])
avg=np.average(stud)
print(avg)
h=np.sum(stud,axis=1)
print(h)
min=np.min(h)
print(min)
max=np.max(h)
print(max)
t=np.sum(stud)
norm=(stud-stud.min())/stud.max()-stud.min()
print(norm)
sub=np.mean(stud,axis=0)
print(sub)

72.88888888888889
[200 250 206]
200
250
[[-44.57894737 -44.73684211 -45.        ]
 [-44.52631579 -44.78947368 -44.47368421]
 [-44.68421053 -44.95789474 -44.61052632]]
[83.33333333 61.33333333 74.        ]
